version: '3'

services:
  bot:
    build: .
    container_name: discord-bot
    depends_on:
      - db
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_HOST_PATH=/usr/share/dotnet/dotnet
      - DOTNET_VERSION=8.0
      - TOKEN=your_bot_token_here
      - AUDIO_SERVICES=true
      - LAVALINK_PASSWORD=youshallnotpass
      - LAVALINK_ADDRESS=http://lavalink:2333
      - LAVALINK_WEBSOCKET=ws://lavalink:2333/v4/websocket
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zenith
      POSTGRES_DB: zenith
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: lavalink
    restart: unless-stopped
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    expose:
      - "2333"
    ports:
      - "2333:2333"

networks:
  lavalink:
    name: lavalink

volumes:
  postgres_data:
