// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReworkZenithBeep.Data;

#nullable disable

namespace ReworkZenithBeep.Data.Migrations.Migrations
{
    [DbContext(typeof(BotContext))]
    partial class BotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReworkZenithBeep.Data.Models.items.ItemGuild", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("ReworkZenithBeep.Data.Models.items.ItemRolesSelector", b =>
                {
                    b.Property<int>("keyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("keyId"));

                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("channelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("emojiButton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("messageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("roleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("keyId");

                    b.HasIndex("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ReworkZenithBeep.Data.Models.items.ItemRolesSelector", b =>
                {
                    b.HasOne("ReworkZenithBeep.Data.Models.items.ItemGuild", "Guild")
                        .WithMany("Roles")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("ReworkZenithBeep.Data.Models.items.ItemGuild", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
